name: First Workflow

on: [push] 

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run python script
        run: echo "Some text"

      - name: Command in Multiline
        run: | 
          python --verison