name: HomeWorkflof

on: push

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Install
          run: | 
            git clone https://github.com/Libovskyy/MyProjects.git

        - name: get-gir
          run: |
            cd MyProjects && ls
            

