name: Learn

on:
  issues:
    types: [edited, deleted]
  pull_request:
    types: [assigned, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: | 
          echo >> Hello World
